# Generated by Django 6.0.5 on 2026-06-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0002_exam_studysession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
