# Generated by Django 6.0.5 on 2026-06-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0003_delete_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_reading.book'),
            preserve_default=False,
        ),
    ]
