# Generated by Django 6.0.5 on 2026-06-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0005_alter_chapter_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='reading_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book_reading.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_reading.chapter'),
        ),
    ]
