# Generated by Django 6.0.5 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0006_readingprogress_reading_model_alter_chapter_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='model',
            field=models.CharField(default=2019, max_length=100),
            preserve_default=False,
        ),
    ]
