# Generated by Django 6.0.5 on 2026-06-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0007_readingprogress_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course')),
            ],
        ),
    ]
