# Generated by Django 6.0.5 on 2026-06-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0008_improve'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='finish_around',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('start_around', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course')),
            ],
        ),
    ]
