# Generated by Django 6.0.5 on 2026-06-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0009_readingprogress_finish_around_readingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_reading.chapter'),
        ),
    ]
