# Generated by Django 6.0.5 on 2026-06-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0011_revise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='improve',
            name='book',
        ),
        migrations.RemoveField(
            model_name='improve',
            name='course',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Improve',
        ),
    ]
