# Generated by Django 6.0.5 on 2026-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0012_remove_improve_book_remove_improve_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AddField(
            model_name='revise',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
