# Generated by Django 6.0.5 on 2026-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0013_readingplan_priority_revise_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revise',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
