# Generated by Django 6.0.5 on 2026-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0014_readingplan_order_revise_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('note', models.TextField()),
            ],
        ),
    ]
