# Generated by Django 6.0.5 on 2026-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0015_otherstudyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='is_postponed',
            field=models.BooleanField(default=False),
        ),
    ]
