# Generated by Django 6.0.5 on 2026-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0016_readingprogress_is_postponed'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='current_chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='model',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
