# Generated by Django 6.0.5 on 2026-06-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0017_readingprogress_current_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='current_chapter',
        ),
    ]
