# Generated by Django 6.0.5 on 2026-06-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0018_remove_readingprogress_current_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherstudyprogress',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_reading.course'),
        ),
    ]
