# Generated by Django 6.0.5 on 2026-06-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0019_otherstudyprogress_page_alter_book_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherstudyprogress',
            name='page',
        ),
    ]
