# Generated by Django 6.0.5 on 2026-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0020_remove_otherstudyprogress_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherstudyprogress',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Postponed'), (4, 'Completed')], default=1),
        ),
    ]
