# Generated by Django 6.0.5 on 2026-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0021_otherstudyprogress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='is_postponed',
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Postponed'), (4, 'Completed')], default=1),
        ),
    ]
