# Generated by Django 6.0.5 on 2026-07-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0022_remove_readingprogress_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='otherstudyprogress',
            options={'verbose_name': 'Other Study Progress', 'verbose_name_plural': 'Other Study Progress'},
        ),
        migrations.AlterModelOptions(
            name='readingplan',
            options={'verbose_name': 'Reading Plan', 'verbose_name_plural': 'Reading Plans'},
        ),
        migrations.AlterModelOptions(
            name='readingprogress',
            options={'verbose_name': 'Reading Progress', 'verbose_name_plural': 'Reading Progress'},
        ),
        migrations.AlterModelOptions(
            name='revise',
            options={'verbose_name': 'Revise', 'verbose_name_plural': 'Revises'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_reading.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='book',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(verbose_name='Chapter number'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='otherstudyprogress',
            name='note',
            field=models.TextField(verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='otherstudyprogress',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Postponed'), (4, 'Completed')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='otherstudyprogress',
            name='topic_name',
            field=models.CharField(max_length=200, verbose_name='Topic name'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_reading.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='start_around',
            field=models.DateField(blank=True, null=True, verbose_name='Start around'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_reading.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='current_page',
            field=models.IntegerField(default=0, verbose_name='Current page'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='finish_around',
            field=models.DateField(blank=True, null=True, verbose_name='Finish around'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='model',
            field=models.CharField(default=0, max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='reading_model',
            field=models.BooleanField(default=False, verbose_name='Reading model'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Postponed'), (4, 'Completed')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_reading.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='possible_date',
            field=models.DateField(blank=True, null=True, verbose_name='Possible date'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, verbose_name='Priority'),
        ),
    ]
