# Generated by Django 6.0.5 on 2026-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingplan',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
