# Generated by Django 6.0.5 on 2026-07-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0023_alter_book_options_alter_chapter_options_and_more'),
        ('writing_plan', '0002_writingplan_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writingplan',
            options={'verbose_name': 'Writing Plan', 'verbose_name_plural': 'Writing Plans'},
        ),
        migrations.AlterField(
            model_name='writingplan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='writingplan',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_reading.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='writingplan',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='writingplan',
            name='possible_date',
            field=models.DateField(blank=True, null=True, verbose_name='Possible date'),
        ),
        migrations.AlterField(
            model_name='writingplan',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, verbose_name='Priority'),
        ),
    ]
