# Generated by Django 6.1 on 2026-08-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_plan', '0003_alter_writingplan_options_alter_writingplan_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingplan',
            name='note',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Note'),
        ),
    ]
