# Generated by Django 5.1.3 on 2026-08-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_plan', '0004_alter_writingplan_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
