# Generated by Django 6.0.5 on 2026-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
