# Generated by Django 6.0.5 on 2026-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_genre_document_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('link', models.CharField()),
            ],
        ),
    ]
