# Generated by Django 6.0.5 on 2026-07-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.genre'),
        ),
    ]
