# Generated by Django 6.1 on 2026-08-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_document_options_alter_documentfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
