# Generated by Django 6.1 on 2026-08-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_description_alter_link_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': [('access_genre', 'Can access this genre')], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
