# Generated by Django 6.1 on 2026-08-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('document', '0007_alter_genre_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='document.genre')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_access_rules', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('genre', 'group'), name='unique_genre_group_access')],
            },
        ),
    ]
