# Generated by Django 6.1 on 2026-08-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_document_owner_link_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
    ]
