# Generated by Django 6.0.5 on 2026-07-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='type',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Warning'), (3, 'Danger')], default=2),
        ),
    ]
