# Generated by Django 6.0.5 on 2026-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guide_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['priority'], 'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='type',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Warning'), (3, 'Danger')], default=2, verbose_name='Type'),
        ),
    ]
