# Generated by Django 5.1.3 on 2026-08-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_guide_options_alter_guide_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
