# Generated by Django 6.0.5 on 2026-07-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookCollection', '0002_book_genre_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('start_around', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_page', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_postponed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finish_around', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.book')),
            ],
        ),
    ]
