# Generated by Django 6.0.5 on 2026-07-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookCollection', '0004_lend_studynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='lend',
            options={'verbose_name': 'Lend', 'verbose_name_plural': 'Lends'},
        ),
        migrations.AlterModelOptions(
            name='readingplan',
            options={'verbose_name': 'Reading Plan', 'verbose_name_plural': 'Reading Plans'},
        ),
        migrations.AlterModelOptions(
            name='readingprogress',
            options={'verbose_name': 'Reading Progress', 'verbose_name_plural': 'Reading Progress'},
        ),
        migrations.AlterModelOptions(
            name='studynote',
            options={'verbose_name': 'Study Note', 'verbose_name_plural': 'Study Notes'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookCollection.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='receiver',
            field=models.CharField(max_length=100, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='return_date',
            field=models.DateField(auto_now=True, verbose_name='Return date'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='start_around',
            field=models.DateField(blank=True, null=True, verbose_name='Start around'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='finish_around',
            field=models.DateField(blank=True, null=True, verbose_name='Finish around'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='is_postponed',
            field=models.BooleanField(default=False, verbose_name='Is postponed'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='reading_page',
            field=models.IntegerField(default=0, verbose_name='Reading page'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCollection.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='note',
            field=models.TextField(max_length=500, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='page',
            field=models.IntegerField(default=0, verbose_name='Page'),
        ),
    ]
