# Generated by Django 6.0.5 on 2026-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='note',
            field=models.TextField(max_length=500),
        ),
    ]
