# Generated by Django 6.0.5 on 2026-06-24 17:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_studynote_page_alter_notes_note_alter_studynote_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Note'),
        ),
    ]
