# Generated by Django 6.0.5 on 2026-07-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0023_alter_book_options_alter_chapter_options_and_more'),
        ('general', '0004_alter_notes_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='studynote',
            options={'verbose_name': 'Study Note', 'verbose_name_plural': 'Study Notes'},
        ),
        migrations.AlterField(
            model_name='studynote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='note',
            field=models.TextField(max_length=500, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='page',
            field=models.IntegerField(default=0, verbose_name='Page'),
        ),
    ]
