# Generated by Django 5.1.3 on 2026-08-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_notes_options_alter_studynote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('bengali', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('familiar', 'Familiar'), ('unfamiliar', 'Unfamiliar'), ('confident', 'Confident')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Word Collection',
                'verbose_name_plural': 'Word Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
