# Generated by Django 5.1.3 on 2026-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_wordcollection_alter_notes_id_alter_studynote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcollection',
            name='english',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
