# Generated by Django 5.1.3 on 2026-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_delete_wordcollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['order'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='notes',
            name='show_on_home_page',
            field=models.BooleanField(default=False, verbose_name='Show on home page'),
        ),
    ]
