# Generated by Django 5.1.3 on 2026-09-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_notes_options_notes_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title'),
        ),
    ]
