# Generated by Django 6.0.5 on 2026-06-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_reading', '0012_remove_improve_book_remove_improve_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course')),
            ],
        ),
        migrations.CreateModel(
            name='Improve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course')),
            ],
        ),
    ]
