# Generated by Django 6.0.5 on 2026-07-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reading', '0023_alter_book_options_alter_chapter_options_and_more'),
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='improve',
            options={'verbose_name': 'Improve', 'verbose_name_plural': 'Improve'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(verbose_name='Exam date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='improve',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='improve',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reading.course', verbose_name='Course'),
        ),
    ]
