# Generated by Django 6.1 on 2026-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0003_alter_exam_id_alter_improve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='improve',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
