# Generated by Django 5.1.3 on 2026-10-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0004_alter_exam_id_alter_improve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
