# Generated by Django 5.1.3 on 2026-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.CharField(max_length=100, verbose_name='Base Form')),
                ('past', models.CharField(max_length=100, verbose_name='Past Form')),
                ('pp', models.CharField(max_length=100, unique=True, verbose_name='Past Participle')),
                ('status', models.CharField(choices=[('new', 'New'), ('familiar', 'Familiar'), ('unfamiliar', 'Unfamiliar'), ('confident', 'Confident')], default='new', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
