# Generated by Django 5.1.3 on 2026-09-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_verbform'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vocabulary Type',
                'verbose_name_plural': 'Vocabulary Types',
                'db_table': 'vocabulary_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='wordcollection',
            name='vocabulary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='vocabulary.vocabularytype', verbose_name='Vocabulary Type'),
        ),
    ]
