# Generated by Django 5.1.3 on 2026-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_vocabularytype_wordcollection_vocabulary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcollection',
            name='example',
            field=models.TextField(blank=True, null=True, verbose_name='Example Sentence'),
        ),
    ]
